version: "3"
services:
  database:
    image: postgres:14-alpine
    container_name: exbbs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exbbs
    networks:
      - default
    ports:
      - 55432:5432
    volumes:
      - exbbs-data:/var/lib/postgresql/data

networks:
  default:
volumes:
  exbbs-data:
