version: "3"
services:
  database:
    image: postgres:14-alpine
    container_name: database-data-twister-com
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data-twister-com
    networks:
      - default
    ports:
      - 55432:5432
    volumes:
      - data-twister-com-db-data:/var/lib/postgresql/data

networks:
  default:
volumes:
  data-twister-com-db-data:
